  name: Run Selenium Tests

  on:
    push:
      branches:
        - main
    pull_request:

  jobs:
    selenium-tests:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome (Version 134.0.6998.35)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_134.0.6998.35-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_134.0.6998.35-1_amd64.deb  

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Extract Chrome Cache
        run: |
          mkdir -p ./tests/cache
          tar -xzf /home/runner/work/eim-map-test/eim-map-test/tests/chrome_cache.tar.gz -C ./tests/cache

      - name: Run Tests with Virtual Display
        run: |
          mkdir -p allure-results
          export DISPLAY=:99
          xvfb-run -a pytest --capture=no --alluredir=allure-results tests/test_checklist.py
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline@latest
          allure generate --clean allure-results -o allure-report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
        continue-on-error: true

      - name: Deploy Allure Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: allure-report
